export const projects = [
  {
    title: 'Toro Clinic Website',
    description:"Toro Clinic is an out patient clinic located in Palapye, Botswana. I developed its  website which plays a vital role in the clinic’s digital marketing and transformation strategy and it makes it easy for clients to schedule appointments online.",
    image: '/images/2.png',
    tags: ['HTML','Bootstrap','JavaScript','PHP','MySQL'],
    live: 'https://toroclinic.com',
    code: '',
    id: 0,
  },
  {
    title: 'NFT Market Place App',
    description: "A react native(UI), FastAPI (Server) and MySQL(DB) non-fungible token market place where users can create NFTs and bid on other users' NFTs.",
      image: '/images/1.png',
      tags: ['Expo', 'MySQL', 'FastAPI'],
    live: 'https://github.com/anothermorena/nft-marketplace',
    code: '',
    id: 1,
  },
  {
    title: 'Breast Cancer Classification PWA',
    description: "An end-to-end PWA and a supervised machine learning (random forest) project which classifies patients’ abnormal masses of cells (tumors) as either benign (non-cancerous) or malignant (cancerous). The model had a 0.99 AUC score, 0.99 Accuracy, 1.0 Precision, 0.97 Recall, and a 0.99 F1-score for class 0 (Cancerous Tumors).",
      image: '/images/3.png',
      tags: ['React','Python','FastAPI','Sklearn'],
    code: 'https://github.com/anothermorena/Breast-Cancer-Classification',
    live: 'https://bcca.vercel.app/',
    id: 2,
  },
  {
    title: 'Medical Insurance Cost Prediction PWA',
    description: "Another end-to-end PWA and a machine learning (linear regression) project to predict the medical insurance cost of a person. The model yielded an R2 score of 0.79",
    image: '/images/4.png',
    tags: ['React','Python','FastAPI','Sklearn'],
    code: 'https://github.com/anothermorena/Medical-Insurance-Cost-Prediction',
    live: 'https://micpa.vercel.app/',
    id: 3,
  },
  {
    title: 'Pneumonia Prediction PWA',
    description: "This is an end-to-end PWA and a convolutional neural network (CNN) project that classifies chest x-ray images of patients with lung disease (pneumonia) and those who do not have lung disease (normal). The model had a 0.90 AUC score, 0.91 Accuracy, 0.92 Precision, 0.94 Recall, and a 0.91 F1-score for class 0 (Pneumonia).",
    image: '/images/5.png',
    tags: ['React','Python','FastAPI','Keras', 'Tensorflow'],
    code: 'https://github.com/anothermorena/pneumonia-prediction',
    live: 'https://ppa-virid.vercel.app/',
    id: 4,
  },
  {
    title: 'Ithute Motswana Website',
    description: "This was a scholarship application portal. I recruited like-minded Batswana and established an NGO, developed its website and social platforms. We sought to help Batswana get international scholarships and managed to help several students win fully funded scholarships.",
    image: '/images/6.png',
    tags: ['HTML','Materialize CSS','jQuery','PHP','MySQL'],
    code: 'https://github.com/anothermorena/Ithute-Motswana',
    live: 'https://ithute-motswana.000webhostapp.com/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my software engineering journey.', },
  { year: 2016, text: 'Got an information technology internship at Always Open Clinic.', },
  { year: 2018, text: 'Got a Bachelors degree in Clinical Informatics.'},
  { year: 2018, text: 'Started my CTO role at Toro Clinic.', },
  { year: 2021, text: 'Got a Masters degree in Biomedical Engineering specializing in Bioinformatics and Machine Learning.', },
];